import type {
  DeltaSummary,
  FunctionDelta,
  ProjectReport,
  Severity,
} from "./types.js";

const SEVERITY_LABEL: Record<Severity, string> = {
  low: "Low",
  moderate: "Moderate",
  high: "High",
  veryHigh: "Very high",
};

/**
 * Render a {@link ProjectReport} as a GitHub-flavoured Markdown summary — the
 * format you paste into a pull request, issue, or CI comment. Includes the
 * headline metrics, severity distribution, the top hot spots, and (when churn
 * ran) the risk ranking. Pass a {@link DeltaSummary} to prepend a baseline
 * comparison — ideal for a PR comment that shows what the change did.
 */
export function renderMarkdown(report: ProjectReport, delta?: DeltaSummary | null): string {
  const { summary } = report;
  const out: string[] = [];

  out.push(`# Complexity Radar`);
  out.push("");
  out.push(`\`${report.root}\``);
  out.push("");

  if (delta) renderDelta(out, delta);

  out.push(
    `| Files | Functions | LOC | Avg cx | Max cx | Avg cog | Max cog |`,
    `| ----: | --------: | --: | -----: | -----: | ------: | ------: |`,
    `| ${fmt(summary.fileCount)} | ${fmt(summary.functionCount)} | ${fmt(summary.totalLoc)} | ${summary.avgComplexity.toFixed(1)} | ${summary.maxComplexity} | ${summary.avgCognitive.toFixed(1)} | ${summary.maxCognitive} |`,
    "",
  );

  out.push(
    `**Severity:** ` +
      (["low", "moderate", "high", "veryHigh"] as Severity[])
        .map((s) => `${SEVERITY_LABEL[s]} ${summary.severity[s]}`)
        .join(" · "),
    "",
  );

  if (summary.threshold !== null) {
    const verdict = summary.overThreshold > 0 ? "⚠️" : "✅";
    out.push(
      `${verdict} ${summary.overThreshold} function(s) over the complexity threshold of ${summary.threshold}.`,
      "",
    );
  }

  out.push(`## Hot spots`);
  out.push("");
  if (summary.hotspots.length === 0) {
    out.push("_No functions detected._", "");
  } else {
    out.push(
      `| Complexity | Cognitive | Function | File | Lang |`,
      `| ---------: | --------: | -------- | ---- | ---- |`,
    );
    for (const h of summary.hotspots) {
      out.push(
        `| ${h.complexity} | ${h.cognitive} | \`${escapeCell(h.name)}\` | ${escapeCell(h.relPath)}:${h.line} | ${escapeCell(h.language)} |`,
      );
    }
    out.push("");
  }

  const churn = summary.churn;
  if (churn && churn.hotspots.length > 0) {
    const window = churn.since ? `since ${churn.since}` : "full history";
    out.push(`## Risk hot spots`);
    out.push("");
    out.push(`Complexity × git churn · ${window}`, "");
    out.push(
      `| Risk | Complexity | Churn | Function | File |`,
      `| ---: | ---------: | ----: | -------- | ---- |`,
    );
    for (const h of churn.hotspots) {
      out.push(
        `| ${fmt(h.risk ?? 0)} | ${h.complexity} | ${h.commits ?? 0} | \`${escapeCell(h.name)}\` | ${escapeCell(h.relPath)}:${h.line} |`,
      );
    }
    out.push("");
  }

  out.push(
    `<sub>Generated by Complexity Radar. Cyclomatic (1 + decision points) and ` +
      `cognitive (nesting-weighted) complexity are computed heuristically, so treat ` +
      `scores as directional.</sub>`,
  );

  return out.join("\n") + "\n";
}

const STATUS_LABEL: Record<FunctionDelta["status"], string> = {
  worsened: "⚠️ worse",
  new: "🆕 new",
  removed: "🗑️ removed",
  improved: "✅ better",
  same: "same",
};

/** Render the baseline-comparison section into `out`. */
function renderDelta(out: string[], delta: DeltaSummary): void {
  out.push(`## Baseline comparison`);
  out.push("");
  if (delta.baselineGeneratedAt) {
    out.push(`Compared against baseline from ${delta.baselineGeneratedAt}.`, "");
  }

  const verdict = delta.regressions.length > 0 ? "⚠️" : "✅";
  const net =
    delta.totalComplexityDelta === 0
      ? "no net change in total complexity"
      : `net complexity ${signed(delta.totalComplexityDelta)}`;
  out.push(
    `${verdict} **${delta.regressions.length} regression(s)** · ${net} · ` +
      `${delta.worsened} worse · ${delta.improved} better · ` +
      `${delta.added} new · ${delta.removed} removed`,
    "",
  );

  // Show regressions when present, otherwise the notable improvements/changes.
  const rows = delta.regressions.length > 0 ? delta.regressions : delta.changes.slice(0, 10);
  if (rows.length === 0) {
    out.push("_No function-level changes._", "");
    return;
  }

  out.push(
    `| Change | Complexity | Cognitive | Function | File |`,
    `| ------ | ---------: | --------: | -------- | ---- |`,
  );
  for (const d of rows) {
    out.push(
      `| ${STATUS_LABEL[d.status]} | ${cxCell(d)} | ${cogCell(d)} | ` +
        `\`${escapeCell(d.name)}\` | ${escapeCell(d.relPath)}:${d.line} |`,
    );
  }
  out.push("");
}

/** A "before → after (±delta)" cell for cyclomatic complexity. */
function cxCell(d: FunctionDelta): string {
  if (d.status === "new") return `${d.complexity} (new)`;
  if (d.status === "removed") return `~~${d.baseComplexity}~~`;
  return `${d.baseComplexity} → ${d.complexity} (${signed(d.complexityDelta)})`;
}

function cogCell(d: FunctionDelta): string {
  if (d.status === "new") return String(d.cognitive);
  if (d.status === "removed") return `~~${d.baseCognitive}~~`;
  return `${d.baseCognitive} → ${d.cognitive}`;
}

function signed(n: number): string {
  return n > 0 ? `+${n}` : String(n);
}

/** Escape the characters that would break out of a Markdown table cell. */
function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function fmt(n: number): string {
  return n.toLocaleString("en-US");
}
