import { SEVERITY_THRESHOLDS } from "./analyze.js";
import type { FileReport, ProjectReport, Severity } from "./types.js";

const SEVERITY_LABEL: Record<Severity, string> = {
  low: "Low",
  moderate: "Moderate",
  high: "High",
  veryHigh: "Very high",
};

/** Render a {@link ProjectReport} as a single self-contained HTML document. */
export function renderHtml(report: ProjectReport): string {
  const { summary } = report;
  const generated = new Date(report.generatedAt).toLocaleString();
  const filesWithFns = report.files.filter((f) => f.functions.length > 0);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Complexity Radar — ${escapeHtml(report.root)}</title>
<style>${STYLE}</style>
</head>
<body>
<header class="topbar">
  <div class="brand"><span class="logo">◎</span> Complexity Radar</div>
  <div class="meta">
    <span title="${escapeHtml(report.root)}">${escapeHtml(shortenPath(report.root))}</span>
    <span class="dot">•</span>
    <span>${escapeHtml(generated)}</span>
  </div>
</header>

<main>
  <section class="cards">
    ${card("Files", fmt(summary.fileCount))}
    ${card("Functions", fmt(summary.functionCount))}
    ${card("Lines of code", fmt(summary.totalLoc))}
    ${card("Avg complexity", summary.avgComplexity.toFixed(1))}
    ${card("Max complexity", fmt(summary.maxComplexity), severityFor(summary.maxComplexity))}
    ${thresholdCard(summary.threshold, summary.overThreshold)}
  </section>

  <section class="panel">
    <h2>Severity distribution</h2>
    ${severityBar(summary.severity, summary.functionCount)}
    <p class="legend">
      ${legendItem("low", `≤ ${SEVERITY_THRESHOLDS.moderate - 1}`)}
      ${legendItem("moderate", `${SEVERITY_THRESHOLDS.moderate}–${SEVERITY_THRESHOLDS.high - 1}`)}
      ${legendItem("high", `${SEVERITY_THRESHOLDS.high}–${SEVERITY_THRESHOLDS.veryHigh - 1}`)}
      ${legendItem("veryHigh", `≥ ${SEVERITY_THRESHOLDS.veryHigh}`)}
    </p>
  </section>

  <section class="panel">
    <h2>Hot spots <span class="subtle">worst ${summary.hotspots.length} functions</span></h2>
    <input id="filter" class="filter" type="search" placeholder="Filter by function or file…" aria-label="Filter hot spots">
    ${hotspotTable(report)}
  </section>

  <section class="panel">
    <h2>By language</h2>
    ${languageTable(report)}
  </section>

  <section class="panel">
    <h2>Files <span class="subtle">${filesWithFns.length} with functions</span></h2>
    <div class="files">
      ${filesWithFns.map(fileBlock).join("\n")}
      ${filesWithFns.length === 0 ? '<p class="subtle">No functions were detected.</p>' : ""}
    </div>
  </section>

  <footer class="foot">
    <p>Generated by <strong>Complexity Radar</strong>. Cyclomatic complexity is
    computed heuristically (1 + decision points) without a full parser, so treat
    scores as directional rather than exact — especially for Java and C#.</p>
  </footer>
</main>

<script>${SCRIPT}</script>
</body>
</html>`;
}

function card(label: string, value: string, sev?: Severity): string {
  const cls = sev ? ` sev-${sev}` : "";
  return `<div class="card${cls}"><div class="card-value">${value}</div><div class="card-label">${label}</div></div>`;
}

function thresholdCard(threshold: number | null, over: number): string {
  if (threshold === null) return card("Over threshold", "—");
  const sev: Severity = over > 0 ? "high" : "low";
  return card(`Over threshold (${threshold})`, fmt(over), sev);
}

function severityBar(sev: Record<Severity, number>, total: number): string {
  if (total === 0) return '<div class="bar empty"></div>';
  const seg = (s: Severity) => {
    const pct = (sev[s] / total) * 100;
    if (pct === 0) return "";
    return `<div class="seg seg-${s}" style="width:${pct.toFixed(2)}%" title="${SEVERITY_LABEL[s]}: ${sev[s]}"></div>`;
  };
  return `<div class="bar">${seg("low")}${seg("moderate")}${seg("high")}${seg("veryHigh")}</div>`;
}

function legendItem(sev: Severity, range: string): string {
  return `<span class="leg"><span class="swatch sw-${sev}"></span>${SEVERITY_LABEL[sev]} <span class="subtle">(${range})</span></span>`;
}

function hotspotTable(report: ProjectReport): string {
  if (report.summary.hotspots.length === 0) {
    return '<p class="subtle">Nothing to show.</p>';
  }
  const rows = report.summary.hotspots
    .map(
      (h) => `<tr>
      <td data-sort="${escapeAttr(h.name)}"><code>${escapeHtml(h.name)}</code></td>
      <td data-sort="${escapeAttr(h.relPath)}" class="path"><span title="${escapeHtml(h.relPath)}">${escapeHtml(h.relPath)}</span><span class="subtle">:${h.line}</span></td>
      <td data-sort="${escapeAttr(h.language)}">${escapeHtml(h.language)}</td>
      <td data-type="num" data-sort="${h.complexity}">${badge(h.complexity, h.severity)}</td>
      <td data-type="num" data-sort="${h.loc}">${h.loc}</td>
      <td data-type="num" data-sort="${h.maxNesting}">${h.maxNesting}</td>
      <td data-type="num" data-sort="${h.params}">${h.params}</td>
    </tr>`,
    )
    .join("\n");
  return `<div class="table-wrap"><table class="sortable" id="hotspots">
    <thead><tr>
      <th data-key>Function</th>
      <th data-key>File</th>
      <th data-key>Lang</th>
      <th data-key data-type="num" class="num" aria-sort="descending">Complexity</th>
      <th data-key data-type="num" class="num">LOC</th>
      <th data-key data-type="num" class="num">Nesting</th>
      <th data-key data-type="num" class="num">Params</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table></div>`;
}

function languageTable(report: ProjectReport): string {
  const rows = report.summary.byLanguage
    .map(
      (l) => `<tr>
      <td>${escapeHtml(l.language)}</td>
      <td data-type="num">${l.files}</td>
      <td data-type="num">${l.functions}</td>
      <td data-type="num">${fmt(l.totalLoc)}</td>
      <td data-type="num">${l.avgComplexity.toFixed(1)}</td>
      <td data-type="num">${badge(l.maxComplexity, severityFor(l.maxComplexity))}</td>
    </tr>`,
    )
    .join("\n");
  return `<div class="table-wrap"><table>
    <thead><tr>
      <th>Language</th><th class="num">Files</th><th class="num">Functions</th>
      <th class="num">LOC</th><th class="num">Avg</th><th class="num">Max</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table></div>`;
}

function fileBlock(file: FileReport): string {
  const worst = file.maxComplexity;
  const rows = file.functions
    .slice()
    .sort((a, b) => b.complexity - a.complexity)
    .map(
      (fn) => `<tr>
        <td><code>${escapeHtml(fn.name)}</code> <span class="subtle">:${fn.line}</span></td>
        <td data-type="num">${badge(fn.complexity, fn.severity)}</td>
        <td data-type="num">${fn.loc}</td>
        <td data-type="num">${fn.maxNesting}</td>
        <td data-type="num">${fn.params}</td>
      </tr>`,
    )
    .join("\n");
  return `<details class="file">
    <summary>
      <span class="fname">${escapeHtml(file.relPath)}</span>
      <span class="fmeta">
        <span class="subtle">${file.functions.length} fn · ${file.loc} LOC</span>
        ${badge(worst, severityFor(worst))}
      </span>
    </summary>
    <div class="table-wrap"><table>
      <thead><tr><th>Function</th><th class="num">Complexity</th><th class="num">LOC</th><th class="num">Nesting</th><th class="num">Params</th></tr></thead>
      <tbody>${rows}</tbody>
    </table></div>
  </details>`;
}

function badge(value: number, sev: Severity): string {
  return `<span class="badge b-${sev}">${value}</span>`;
}

function severityFor(complexity: number): Severity {
  if (complexity >= SEVERITY_THRESHOLDS.veryHigh) return "veryHigh";
  if (complexity >= SEVERITY_THRESHOLDS.high) return "high";
  if (complexity >= SEVERITY_THRESHOLDS.moderate) return "moderate";
  return "low";
}

function fmt(n: number): string {
  return n.toLocaleString("en-US");
}

function shortenPath(p: string, max = 60): string {
  return p.length <= max ? p : "…" + p.slice(p.length - max + 1);
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&#39;",
  );
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}

const STYLE = `
:root{
  --bg:#f6f8fa;--panel:#ffffff;--ink:#1f2328;--muted:#656d76;--line:#d0d7de;
  --accent:#0969da;--code:#f6f8fa;
  --low:#1a7f37;--moderate:#9a6700;--high:#bc4c00;--veryHigh:#cf222e;
  --low-bg:#dafbe1;--moderate-bg:#fff8c5;--high-bg:#ffe7ce;--veryHigh-bg:#ffebe9;
}
@media (prefers-color-scheme:dark){
  :root{
    --bg:#0d1117;--panel:#161b22;--ink:#e6edf3;--muted:#8b949e;--line:#30363d;
    --accent:#4493f8;--code:#161b22;
    --low:#3fb950;--moderate:#d29922;--high:#db6d28;--veryHigh:#f85149;
    --low-bg:#12261e;--moderate-bg:#272115;--high-bg:#28170d;--veryHigh-bg:#25171c;
  }
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
code{font-family:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
  background:var(--code);padding:1px 5px;border-radius:5px;font-size:12.5px;}
.topbar{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;
  padding:14px 24px;border-bottom:1px solid var(--line);background:var(--panel);position:sticky;top:0;z-index:5;}
.brand{font-weight:700;font-size:16px;display:flex;align-items:center;gap:8px}
.logo{color:var(--accent);font-size:20px}
.meta{color:var(--muted);font-size:13px;display:flex;gap:8px;align-items:center}
.dot{opacity:.5}
main{max-width:1100px;margin:0 auto;padding:24px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:24px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px}
.card-value{font-size:26px;font-weight:700;line-height:1.1}
.card-label{color:var(--muted);font-size:12.5px;margin-top:4px}
.card.sev-veryHigh .card-value{color:var(--veryHigh)}
.card.sev-high .card-value{color:var(--high)}
.card.sev-moderate .card-value{color:var(--moderate)}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:18px 20px;margin-bottom:20px}
.panel h2{margin:0 0 14px;font-size:15px}
.subtle{color:var(--muted);font-weight:400;font-size:12.5px}
.bar{display:flex;height:14px;border-radius:7px;overflow:hidden;background:var(--code)}
.bar.empty{opacity:.4}
.seg-low{background:var(--low)}.seg-moderate{background:var(--moderate)}
.seg-high{background:var(--high)}.seg-veryHigh{background:var(--veryHigh)}
.legend{display:flex;flex-wrap:wrap;gap:16px;margin:12px 0 0;font-size:12.5px}
.leg{display:flex;align-items:center;gap:6px}
.swatch{width:11px;height:11px;border-radius:3px;display:inline-block}
.sw-low{background:var(--low)}.sw-moderate{background:var(--moderate)}
.sw-high{background:var(--high)}.sw-veryHigh{background:var(--veryHigh)}
.filter{width:100%;max-width:340px;margin-bottom:12px;padding:7px 10px;border:1px solid var(--line);
  border-radius:7px;background:var(--bg);color:var(--ink);font-size:13px}
.table-wrap{overflow-x:auto}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);white-space:nowrap}
th{color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
th.num,td[data-type=num]{text-align:right}
table.sortable th[data-key]{cursor:pointer;user-select:none}
table.sortable th[aria-sort=ascending]::after{content:" ▲";font-size:9px}
table.sortable th[aria-sort=descending]::after{content:" ▼";font-size:9px}
td.path{max-width:340px;overflow:hidden;text-overflow:ellipsis}
tbody tr:hover{background:color-mix(in srgb,var(--accent) 7%,transparent)}
.badge{display:inline-block;min-width:26px;text-align:center;padding:1px 8px;border-radius:20px;
  font-weight:700;font-size:12px}
.b-low{background:var(--low-bg);color:var(--low)}
.b-moderate{background:var(--moderate-bg);color:var(--moderate)}
.b-high{background:var(--high-bg);color:var(--high)}
.b-veryHigh{background:var(--veryHigh-bg);color:var(--veryHigh)}
.files{display:flex;flex-direction:column;gap:8px}
.file{border:1px solid var(--line);border-radius:8px;background:var(--bg)}
.file summary{cursor:pointer;padding:10px 14px;display:flex;justify-content:space-between;
  align-items:center;gap:12px;list-style:none}
.file summary::-webkit-details-marker{display:none}
.file summary:hover{background:color-mix(in srgb,var(--accent) 6%,transparent)}
.fname{font-family:ui-monospace,monospace;font-size:13px;overflow:hidden;text-overflow:ellipsis}
.fmeta{display:flex;align-items:center;gap:12px;flex-shrink:0}
.file[open] summary{border-bottom:1px solid var(--line)}
.file .table-wrap{padding:4px 8px 8px}
.foot{color:var(--muted);font-size:12.5px;border-top:1px solid var(--line);padding-top:16px;margin-top:8px}
`;

const SCRIPT = `
(function(){
  // Generic sortable tables.
  document.querySelectorAll("table.sortable").forEach(function(table){
    var headers = table.querySelectorAll("th[data-key]");
    headers.forEach(function(th, idx){
      th.addEventListener("click", function(){
        var numeric = th.getAttribute("data-type") === "num";
        var current = th.getAttribute("aria-sort");
        var asc = current !== "ascending";
        headers.forEach(function(h){ h.removeAttribute("aria-sort"); });
        th.setAttribute("aria-sort", asc ? "ascending" : "descending");
        var tbody = table.tBodies[0];
        var rows = Array.prototype.slice.call(tbody.rows);
        rows.sort(function(a,b){
          var av = cell(a, idx, numeric), bv = cell(b, idx, numeric);
          if (av < bv) return asc ? -1 : 1;
          if (av > bv) return asc ? 1 : -1;
          return 0;
        });
        rows.forEach(function(r){ tbody.appendChild(r); });
      });
    });
    function cell(row, idx, numeric){
      var td = row.cells[idx];
      var v = td.getAttribute("data-sort");
      if (v === null) v = td.textContent.trim();
      return numeric ? parseFloat(v) || 0 : v.toLowerCase();
    }
  });

  // Hot-spot filter box.
  var filter = document.getElementById("filter");
  if (filter){
    var table = document.getElementById("hotspots");
    filter.addEventListener("input", function(){
      var q = filter.value.toLowerCase();
      Array.prototype.forEach.call(table.tBodies[0].rows, function(row){
        row.style.display = row.textContent.toLowerCase().indexOf(q) === -1 ? "none" : "";
      });
    });
  }
})();
`;
